'use client';

/**
 * The stage machine — decides which shell is on screen.
 *
 * classic → updating → color, with Restart from the colour OS going back.
 * See lib/os/stageStore.ts.
 *
 * COORDINATOR-OWNED. Phase 3 agents fill in the three components this mounts;
 * they do not edit this file.
 */
import { AnimatePresence } from 'framer-motion';
import ClassicShell from '@/components/classic/ClassicShell';
import UpdateTransition from '@/components/classic/UpdateTransition';
import Rishu from '@/components/mascot/Rishu';
import Desktop from '@/components/os/Desktop';
import { useStageStore } from '@/lib/os/stageStore';

export default function Stage() {
  const stage = useStageStore((s) => s.stage);
  const generation = useStageStore((s) => s.generation);

  return (
    <>
      <AnimatePresence mode="wait">
        {stage === 'classic' && <ClassicShell key="classic" />}
        {stage === 'updating' && <UpdateTransition key="updating" />}
        {/* Keyed on generation so a Restart → update cycle remounts the colour
            OS: it replays its own boot and re-opens the Browser, rather than
            silently reusing the previous mount's window state. */}
        {stage === 'color' && <Desktop key={`color-${generation}`} />}
      </AnimatePresence>

      {/* Rishu rides above both shells so the joke survives the transition.
          It renders nothing until its own rare trigger fires. */}
      <Rishu context={stage === 'color' ? 'color' : 'classic'} />
    </>
  );
}
