'use client';

/**
 * Which shell is on screen.
 *
 * The site has two front doors. A visitor always arrives in the 1984 monochrome
 * classic shell; a "Software Update" transition then hands off to the System 7
 * colour OS built in Phase 1. `Restart` from the colour OS goes back.
 *
 * COORDINATOR-OWNED — Phase 3 agents read this store but do not edit this file.
 *
 *   const stage = useStageStore((s) => s.stage);
 *   useStageStore.getState().beginUpdate();
 */
import { create } from 'zustand';

/**
 * classic  → the 1984 black-and-white desktop (the front door, every visit)
 * updating → the dissolve/morph transition playing
 * color    → the Phase 1 System 7 colour OS
 */
export type Stage = 'classic' | 'updating' | 'color';

interface StageStore {
  stage: Stage;
  /**
   * Counts how many times the colour OS has been entered. The colour Desktop
   * keys off this so a Restart → update cycle re-runs its own boot and re-opens
   * the Browser, rather than silently reusing the previous mount.
   */
  generation: number;
  /** Classic → transition. Called when the user accepts the software update. */
  beginUpdate: () => void;
  /** Transition → colour OS. Called when the transition animation finishes. */
  finishUpdate: () => void;
  /** Colour OS → classic. Wired to Restart in the logo menu. */
  restart: () => void;
}

export const useStageStore = create<StageStore>((set) => ({
  stage: 'classic',
  generation: 0,

  beginUpdate: () => set((s) => (s.stage === 'classic' ? { stage: 'updating' } : s)),

  finishUpdate: () =>
    set((s) =>
      s.stage === 'updating'
        ? { stage: 'color', generation: s.generation + 1 }
        : s,
    ),

  restart: () => set({ stage: 'classic' }),
}));
